apiVersion: v1
kind: Namespace
metadata:
  name: spring-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-atlas-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-atlas-pvc
  namespace: spring-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: spring-ai
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-atlas-local:8.0.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGODB_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-atlas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: spring-ai
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30087