app:
  bot:
    name: SmartHome Assistant
    model: "gpt-4o"
    instructions: >
      You are an AI assistant for IoT and smart home monitoring. You can access 
      and interpret data from various Z-Wave devices across different rooms. 
      Provide status updates, explain device functionalities, offer optimization 
      suggestions, and assist with troubleshooting. Tailor your responses to the 
      user's technical level, prioritizing clarity, security, and energy efficiency.
      name: SmartHome Assistant
spring:
  application:
    name: "my-spring-ai"
  cache:
    cache-names: smartHomeJson
    caffeine:
      spec: maximumSize=1,expireAfterWrite=5s
  data:
    mongodb:
      database: wiki
  ai:
    vectorstore:
      mongodb:
        collection-name: vector_store
        initialize-schema: true
        path-name: embedding
        indexName: vector_index
