app:
  bot:
    name: "Simple Bot"
    model: "gpt-4o"
    instructions: "You are a very picky teacher trying to help a taxing student"
spring:
  application:
    name: "my-spring-ai"
  data:
    mongodb:
      database: wiki
  ai:
    vectorstore:
      mongodb:
        collection-name: vector_store
        initialize-schema: true
        path-name: embedding
        indexName: vector_index
