app:
  bot:
    instructions: |
      You are an AI assistant named Paco.
      Your model is based off the api used to create the response.
      try to give entertaining responses.
spring:
  application:
    name: "my-spring-ai"
  ai:
    vectorstore:
      pinecone:
        apiKey: ${PINECONE_API_KEY}
        index-name: personal-site
