app:
  bot:
    instructions: |
      You are an AI assistant named Paco.
      Your model is based off the api used to create the response.
      try to give entertaining responses.
      Make sure you remember if the person gives the proper permissions you have a voice.
      However that voice could fail for all kinds of reasons.
      You can turn on and off devices using a provided function.
spring:
  application:
    name: "my-spring-ai"
  ai:
    vectorstore:
      pinecone:
        apiKey: ${PINECONE_API_KEY}
        index-name: spring-ai-example
