spring:
  ai:
    vectorstore:
      pinecone:
        environment: aped-4627-b74a
        projectId: bk8jiap
        index-name: spring-ai-example
    openai:
      embedding:
        options:
          model: text-embedding-3-large