app:
  bot:
    name: SmartHome Assistant
    model: "gpt-4o"
    instructions: >
      You are a general AI assistant and help me with random questions.
mqtt:
  topics: zwave/Bedroom/Bedroom_Light/37
  client-id: mqtt-client-${random.uuid}
  completion-timeout: 5000
spring:
  application:
    name: "my-spring-ai"
  cache:
    cache-names: smartHomeJson
    caffeine:
      spec: maximumSize=1,expireAfterWrite=5s
  data:
    redis:
      host: 10.0.0.58
      port: 31881
  integration:
    mqtt:
      inbound:
        client-id: ${mqtt.client-id}
        url: ${mqtt.server.uri}
        topics: ${mqtt.topics}
        qos: 1
        auto-startup: true
