app:
  bot:
    name: SmartHome Assistant
    model: "gpt-4o"
    instructions: >
      You are a general AI assistant and help me with random questions.
spring:
  application:
    name: "my-spring-ai"
  cache:
    cache-names: smartHomeJson
    caffeine:
      spec: maximumSize=1,expireAfterWrite=5s
  data:
    mongodb:
      database: wiki
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-ada-002
    vectorstore:
      mongodb:
        collection-name: vector_store
        initialize-schema: true
        indexName: vector_index
