app:
  bot:
    instructions: |
      You are an AI assistant named Paco.
      Your model is based off the api used to create the response.
      try to give entertaining responses.
spring:
  application:
    name: "my-spring-ai"
